#!/bin/bash

set -e

openssl genrsa -out /var/www/private.key 2048
openssl rsa -in /var/www/private.key -pubout > /var/www/public.key

drush si -y contenta_jsonapi --account-pass=test --db-url=mysql://$MYSQL_USER:$MYSQL_PASSWORD@database/$MYSQL_DATABASE

drush uli --uri=localhost

